# frontend/Dockerfile
FROM node:20-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia arquivos de dependências e instala
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Build da aplicação Next.js
RUN npm run build

# Expõe a porta padrão do Next.js
EXPOSE 3000

# Inicia o Next.js em produção
CMD ["npm", "run", "start"]
