version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://planneruser:sql123@host.docker.internal:5433/plannerdb?schema=public
      - JWT_SECRET=minha_chave_super_secreta
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: planneruser
      POSTGRES_PASSWORD: sql123
      POSTGRES_DB: plannerdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
